# Oxford-IIIT Pet Dataset Augmentation Configuration

# Cat augmentation parameters (more aggressive)
cat:
  # Spatial transforms
  horizontal_flip_prob: 0.5
  scale_limit: 0.15
  rotate_limit: 15
  shift_limit: 0.1
  shift_scale_rotate_prob: 0.8
  
  # Elastic transforms
  elastic_transform_prob: 0.3
  elastic:
    alpha: 40
    sigma: 4
    alpha_affine: 15
    prob: 0.6
  grid_distortion:
    num_steps: 5
    distort_limit: 0.2
    prob: 0.5
  optical_distortion:
    distort_limit: 0.2
    shift_limit: 0.15
    prob: 0.5
  
  # Pixel-level transforms
  color_transform_prob: 0.8
  brightness_contrast:
    brightness_limit: 0.2
    contrast_limit: 0.2
    prob: 0.8
  hsv:
    hue_shift_limit: 10
    sat_shift_limit: 30
    val_shift_limit: 20
    prob: 0.5
  rgb_shift:
    r_shift_limit: 15
    g_shift_limit: 15
    b_shift_limit: 15
    prob: 0.5
  
  # Noise and blur
  noise_transform_prob: 0.4
  gauss_noise:
    var_limit: [10, 30]
    prob: 0.5
  gaussian_blur:
    blur_limit: 3
    prob: 0.4
  motion_blur:
    blur_limit: 3
    prob: 0.4
  
  # Lighting variations
  lighting_transform_prob: 0.3
  shadow:
    prob: 0.3
  sunflare:
    prob: 0.2

# Dog augmentation parameters (more conservative)
dog:
  # Spatial transforms
  horizontal_flip_prob: 0.5
  scale_limit: 0.1
  rotate_limit: 10
  shift_limit: 0.05
  shift_scale_rotate_prob: 0.5
  
  # Pixel-level transforms
  color_transform_prob: 0.6
  brightness_contrast:
    brightness_limit: 0.15
    contrast_limit: 0.15
    prob: 0.7
  hsv:
    hue_shift_limit: 5
    sat_shift_limit: 20
    val_shift_limit: 15
    prob: 0.4
  
  # Noise and blur
  noise_transform_prob: 0.3
  gauss_noise:
    var_limit: [5, 20]
    prob: 0.3
  gaussian_blur:
    blur_limit: 3
    prob: 0.3